# Generated by Django 4.1.7 on 2023-03-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key_interest',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
