# Generated by Django 4.1.7 on 2023-03-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_key_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
