# Generated by Django 4.1.7 on 2023-03-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_skill_remove_mymodeldescription_my_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('company', models.CharField(blank=True, default=None, max_length=200)),
                ('description', models.TextField(blank=True, default=None)),
            ],
        ),
    ]
