# Generated by Django 4.1.7 on 2023-03-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('journal', models.TextField()),
                ('url', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
    ]
