# Generated by Django 4.1.7 on 2023-03-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
