# Generated by Django 4.1.7 on 2023-03-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_education_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='phone',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
