# Generated by Django 4.1.7 on 2023-03-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
