# Generated by Django 4.1.7 on 2023-03-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_experience_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
