# Generated by Django 4.1.7 on 2023-03-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_certification_date_project_date_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
