# Generated by Django 4.1.7 on 2023-03-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_education_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
